/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-c4fm
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_C4FM_API_H
#define INCLUDED_C4FM_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_c4fm_EXPORTS
#define C4FM_API __GR_ATTR_EXPORT
#else
#define C4FM_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_C4FM_API_H */
