/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bernoulli_source_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ee7ba3d5a68e9c7c9b92923dacfe3ff0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/c4fm/bernoulli_source_b.h>
// pydoc.h is automatically generated in the build directory
#include <bernoulli_source_b_pydoc.h>

void bind_bernoulli_source_b(py::module& m)
{

    using bernoulli_source_b    = gr::c4fm::bernoulli_source_b;


    py::class_<bernoulli_source_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bernoulli_source_b>>(m, "bernoulli_source_b", D(bernoulli_source_b))

        .def(py::init(&bernoulli_source_b::make),
           D(bernoulli_source_b,make)
        )
        



        ;




}








